# Generated by Django 4.0.4 on 2022-05-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_rename_lastname_family_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
