# Generated by Django 4.0.4 on 2022-05-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_family_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='nacimiento',
            field=models.FloatField(),
        ),
    ]
