# Generated by Django 4.0.4 on 2022-05-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_alter_family_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='parentesco',
            field=models.CharField(max_length=30),
        ),
    ]
