# Generated by Django 4.0.4 on 2022-05-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_alter_family_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
