# Generated by Django 4.0.4 on 2022-05-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_alter_family_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='edad',
            field=models.DateField(),
        ),
    ]
